name: FastReload
version: ${project.version}
main: com.mikedeejay2.fastreload.FastReload
api-version: 1.16
authors: [ Mikedeejay2 ]
description: World's fastest reload command. 

commands:
  fastreload:
    description: World's fastest reload command
    permission: fastreload.use
    aliases:
      - reload
      - rl
      - r
  fastreloadrc:
    description: Config reload command for Fast Reload
    permission: fastreload.reloadconfig
    aliases:
      - frrc

permissions:
  fastreload.use:
    description: Permission for fast reloading